[hinting]
BLUEZONE_WIDTH = 60
PPEM_MIN = 15
PPEM_MAX = 20
CANONICAL_STEM_WIDTH = [[12,60],[40,60]]
CANONICAL_STEM_WIDTH_DENSE = [[12,60],[40,60]]
STEM_SIDE_MIN_RISE = 60
STEM_CENTER_MIN_RISE = 60
BOTTOM_UNIFY_FORCE_DIAG = [[15,100]]
TOP_UNIFY_FORCE = [[15,100]]
TOP_UNIFY_FORCE_DIAG = [[15,100]]
BLUEZONE_BOTTOM_CENTER = -143
BLUEZONE_BOTTOM_LIMIT = -143
BLUEZONE_TOP_CENTER = 862
BLUEZONE_TOP_LIMIT = 862
RISE = [[15,10]]
SINK = [[15,10]]
GRAVITY = [[15,10]]
CONCENTRATE = [[15,100]]
TOP_CUT = [[15,1]]
BOTTOM_CUT = [[15,1]]